# Generated by Django 4.2.3 on 2023-08-01 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0004_alter_comentario_autor_alter_publicaciones_creador'),
        ('usuarios', '0002_remove_user_domicilio_remove_user_es_colaborador_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
