# Generated by Django 4.2.2 on 2023-07-29 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_user_groups_alter_user_user_permissions'),
        ('usuarios', '0002_rename_es_admin_user_es_colaborador'),
    ]

    operations = [
    ]
