# Generated by Django 4.2.2 on 2023-07-31 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_user'),
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_autor', to='usuarios.user'),
        ),
        migrations.AlterField(
            model_name='publicaciones',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posteos_creador', to='usuarios.user'),
        ),
    ]
