# Generated by Django 4.2.2 on 2023-07-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='categoria',
            field=models.CharField(default='coding', max_length=255),
        ),
    ]
