# Generated by Django 4.2.3 on 2023-07-31 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('publicaciones', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='usuarios.user'),
        ),
        migrations.AlterField(
            model_name='publicaciones',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posteos_usuario', to='usuarios.user'),
        ),
    ]
