# Generated by Django 4.2.3 on 2023-08-02 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0002_alter_publicaciones_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nombre',
            new_name='username',
        ),
    ]
