# Generated by Django 4.2.3 on 2023-08-05 01:00
# Generated by Django 4.2.3 on 2023-08-05 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0005_alter_publicaciones_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaciones',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
