# Generated by Django 4.2.3 on 2023-08-02 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0005_alter_publicaciones_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaciones',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagen'),
        ),
    ]
