# Generated by Django 4.2.3 on 2023-08-05 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0006_publicaciones_imagen_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='publicaciones',
            name='update',
            field=models.DateField(auto_now_add=True),
        ),
    ]
